from gitCommit import GitCommit
from gitObjects import *
from gitRef import ref_create


class GitTag(GitCommit):
    fmt = b"tag"


def tag_create(repo, name, ref, create_object=False):
    """Creates a tag ,both soft and hard tag ,
    Execution steps :
        1-find the object ref,
        2-check the required tag type ,
        if it's a hard tag:
            1.a-instantiate the tag obj,
            1.b-build the object:
        else :
            only make a file in the refs/

    """
    # 1
    sha = object_find(repo, ref)

    if create_object:
        tag = GitTag()
        tag.kvlm = dict()
        tag.kvlm[b"object"] = sha.encode()
        tag.kvlm[b"type"] = b"commit"
        tag.kvlm[b"tag"] = name.encode()
        tag.kvlm[b"tagger"] = b"Wyag <wyag@example.com>"
        tag.kvlm[None] = (
            b"A tag generated by wyag, which won't let you customize the message!\n"
        )
        tag_sha = object_write(tag, repo)
        ref_create(repo, "tags/" + name, tag_sha)
    else:
        ref_create(repo, "tags/", sha)
